### ISSUE TITLE
Mistakes/improvements in ggplot-intro workshop

### ISSUE THREAD

**Issue by bpbond** [JGCRI/Rworkshops#4]
* Use of `aes()` versus not (`geom_point(color = "red")`) -- needs to be introduced earlier
* geom_hex / geom_area tabset typo
* Could use a little more time--for questions at the end of each section
* "..and what are the data like?" What did I mean by this?

**Comment by bpbond** [comment]
Allow a bit more time so can take any questions section by section.

**Comment by bpbond** [comment]
@stephpenn1 with regard to the [uploading error issue](https://github.com/rstudio/rsconnect/issues/450) what do you think we should do? I've experimented with reducing graphic file sizes but don't think I can get it under 16 MB. 

Split the material into parts? Ugh.

**Comment by bpbond** [comment]
I played a bunch with graphic file sizes and resolutions, and decided yes, the best solution is to split the material into two pieces.

**Comment by stephpenn1** [comment]
Nice, I think that was a good solution!
